### ISSUE TITLE
universal-cli and ng2-meta issue

### ISSUE THREAD

**Issue by derridHeidegger** [vinaygopinath/ng2-meta#34]
i get this error and not sure why:
`Error encountered resolving symbol values sta
tically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported fu
nction, resolving symbol AppModule in C:/xampp/htdocs/universaltest3/src/app/app.browser.module.ts, resolving symbol Ap
pModule in C:/xampp/htdocs/universaltest3/src/app/app.browser.module.ts`
and before i use ng2-meta i could go to source code and see the page. after i only get:
`<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Universaltest3</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="http://localhost:35729/livereload.js?snipver=1"></script>
<link href="styles.bundle.css" rel="stylesheet"></head>
<body>
  <app-root>Loading...</app-root>
<script type="text/javascript" src="inline.bundle.js"></script><script type="text/javascript" src="vendor.bundle.js"></script><script type="text/javascript" src="client.bundle.js"></script></body>
</html>`

**Comment by opteamix-ppalanisamy** [comment]
Even i'm also getting similar kind of issue in angular CLI.

client?93b6:80 Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in src/app/app.module.ts, resolving symbol AppModule in src/app/app.module.ts

any help will be appreciated.

**Comment by arielcamino** [comment]
Same issue here, also I can't generate the build because of this issue:

```
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /src/app/app.browser.module.ts, resolving symbol AppModule in /src/app/app.browser.module.ts
    at simplifyInContext (/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at AotPlugin.getNgModuleMetadata (/node_modules/@ngtools/webpack/src/plugin.js:330:41)
    at AotPlugin._processNgModule (/node_modules/@ngtools/webpack/src/plugin.js:271:42)
    at /node_modules/@ngtools/webpack/src/plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: bundle is now INVALID.(node:10586) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
(node:10586) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'toString' of undefined
```

**Comment by derridHeidegger** [comment]
anybody?

**Comment by arielcamino** [comment]
Hi guys, I'm finally using this version which is working with angular-universal:

https://gist.github.com/orgbx/af6a2920b5d66a5e04972719f46cb71f

it seems to be a simplified version, the only issue is that it is duplicating metadata when you click on router links (I think it will not affect google crawling). I did some modifications to check if a metadata tag exist before appending a new item, if you want I can also share my version.

I suppose that this will be added to the angular core soon.

**Comment by wasteCleaner** [comment]
@derridHeidegger I solve this problem: https://gist.github.com/wasteCleaner/205c818fd57d120dab46a2ae617e45ac

**Comment by derridHeidegger** [comment]
hi @wasteCleaner 
i have tried it and two things,even though i don't get any errors:
1- each time i click on a router link it add instead of replace.
![screenshot 169](https://cloud.githubusercontent.com/assets/1025218/23100839/b08b1ace-f692-11e6-94a7-cdb88c28af54.png)

2- and this is more important. if i view page source none of the meta tags are there.and since i'm using universal with server side rendering, shouldn't we see the meta tags there for seo and link previews for sharing? at least as i understood it.

**Comment by spencer1573** [comment]
yeah.. works locally but freaks out when you ng build --prod with version @angular version ~2.4.0
